-- local utils = require('custom.utils')
--
-- vim.pack.add { utils.gh '3rd/image.nvim' }
--
-- require('image').setup {
--   enabled = false,
--   backend = 'kitty',
--   processor = 'magick_cli',
--   integrations = {
--     markdown = { enabled = true },
--   },
--   max_width_window_percentage = nil,
--   max_height_window_percentage = 50,
--   hijack_file_patterns = { '*.png', '*.jpg', '*.jpeg', '*.gif', '*.svg', '*.webp', '*.avif' },
-- }
